# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-19 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DouyinMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douyincount', models.IntegerField(default=0, verbose_name='抖音私信计数器')),
            ],
        ),
        migrations.CreateModel(
            name='QuickHandMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickhandcount', models.IntegerField(default=0, verbose_name='抖音私信计数器')),
            ],
        ),
    ]
