# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-25 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DouyinCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcommentcount', models.IntegerField(default=0, verbose_name='抖音私评论数器')),
            ],
        ),
        migrations.CreateModel(
            name='GuimiquanCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guimicommentcount', models.IntegerField(default=0, verbose_name='闺蜜评论数器')),
            ],
        ),
        migrations.CreateModel(
            name='GuimiquanMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guimimessagecount', models.IntegerField(default=0, verbose_name='闺蜜私信计数器')),
            ],
        ),
        migrations.CreateModel(
            name='QuickHanaccountProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=20, verbose_name='账号密码')),
                ('isUse', models.BooleanField(default=False, verbose_name='是否在使用')),
                ('islock', models.BooleanField(default=False, verbose_name='是否封号')),
            ],
        ),
        migrations.CreateModel(
            name='QuickHandCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qcommentcount', models.IntegerField(default=0, verbose_name='快手评论计数器')),
            ],
        ),
        migrations.CreateModel(
            name='xiguaCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiguacommentcount', models.IntegerField(default=0, verbose_name='西瓜评论数器')),
            ],
        ),
        migrations.CreateModel(
            name='xiguaMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiguamessagecount', models.IntegerField(default=0, verbose_name='西瓜私信计数器')),
            ],
        ),
        migrations.RenameField(
            model_name='douyinmessagemodel',
            old_name='douyincount',
            new_name='dmessagecount',
        ),
        migrations.RemoveField(
            model_name='quickhandmessagemodel',
            name='quickhandcount',
        ),
        migrations.AddField(
            model_name='quickhandmessagemodel',
            name='qmessagecount',
            field=models.IntegerField(default=0, verbose_name='快手私信计数器'),
        ),
    ]
